spring:
  application:
    name: mybatis-demo
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  boot:
    admin:
      client:
        url: "http://localhost:8087"
        instance:
          name: "mybatis"

mybatis:
  type-aliases-package: com.modianli.mybatis.bean
  #BaseTypeHandlertype-handlers-package: com.modianli.mybatis.interceptor
server:
  port: 9999




management.endpoints.web.exposure.include: "*"

